[package]
name = "regress"
version = "0.3.0"
authors = ["ridiculousfish <corydoras@ridiculousfish.com>"]
description = "A regular expression engine targeting EcmaScript syntax"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ridiculousfish/regress"
keywords = ["regex", "regexp"]
edition = "2018"
readme = "README.md"

[workspace]
members = ["regress-tool", "gen-unicode", "."]
default-members = ["regress-tool", "."]

[profile.release]

[features]
default = ["backend-pikevm"]

# Enables the PikeVM backend.
backend-pikevm = []

# Prefers indexes to pointers for bytecode IP and string positions, for the paranoid.
index-positions = []

# Prohibits all uses of unsafe code, for the paranoid.
prohibit-unsafe = []

[dependencies]
memchr = "2.3.3"
